<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AuraDental.Data\AuraDental.Infraestructura.csproj" />
    <ProjectReference Include="..\AuraDental.Services\AuraDental.Aplicacion.csproj" />
  </ItemGroup>

</Project>
